### ISSUE TITLE
开源库作者推荐：ssseasonnn

### ISSUE THREAD

**Issue by wosika** [getActivity/AndroidGithubBoss#4]
他的首页：https://github.com/ssseasonnn
他的开源库，文档编写完善，代码风格优雅。

凭借RxDownload一个项目斩获4.1k的star。
https://github.com/ssseasonnn/RxDownload
除了RxDownload项目，还有很多kotlin编写的android开源库，推荐上榜~

**Comment by getActivity** [comment]
已加入，多谢小伙子的推荐
