### ISSUE TITLE
收到，多谢小伙子的建议，另外一个我们应该正视事实，开源项目不维护是一件非常正常的事情，换一门编程语言差不多也这样，只是看个人怎么去看待这个事情。

### ISSUE THREAD

**Issue by xuxinjiang** [getActivity/AndroidGithubBoss#5]
收到，多谢小伙子的建议，另外一个我们应该正视事实，开源项目不维护是一件非常正常的事情，换一门编程语言差不多也这样，只是看个人怎么去看待这个事情。

_Originally posted by @getActivity in https://github.com/getActivity/AndroidGithubBoss/issues/1#issuecomment-1073524693_

**Comment by getActivity** [comment]
@xuxinjiang 重复的问题不要在两个地方提
